[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"
'|' = '|'

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]